### PR TITLE
Update index.js to support "sameSite === 'Unset'"

### PR DESCRIPTION
**Pull request by AKushWarrior**
As per issue #100 ...

### CODE REVIEW

**Comment by dougwilson** [comment]
This module only supports the values as defined in the RFC: https://tools.ietf.org/html/draft-ietf-httpbis-rfc6265bis-03#section-4.1.2.7

If you can link to the RFC that adds this new value, we can re-consider 👍

**Comment by AKushWarrior** [comment]
Look at the last sentence of this section from IETF: https://tools.ietf.org/id/draft-ietf-httpbis-rfc6265bis-03.html#the-samesite-attribute

The default should not be a TypeError, it should be the same behavior as 'None'

**Comment by dougwilson** [comment]
> The default should not be a TypeError, it should be the same behavior as 'None'

That wording is in regards to _parsing_ the attribute's value, not serializing.

**Comment by AKushWarrior** [comment]
Okay, I see now. This PR and issue should be for my parsing library :/

Have a good day!

**Pull request closed without merging**
