### PR TITLE
Add ESM compatibility

### PR DESCRIPTION
**Pull request by benmccann**
Closes https://github.com/jshttp/cookie/issues/127

### CODE REVIEW

**Review by dougwilson — CHANGES_REQUESTED** [review]
Thanks @benmccann ! I flagged this as `needs tests` since it seems there are no tests added. At the very least, I don't even know how to test by hand, but ideally the CI would perform the tests to prevent regressions.

**Comment by dougwilson** [comment]
Also looks like `npm run lint` no longer lints the module's source, just the tests.

**Comment by benmccann** [comment]
Thanks. I rebased against `master`. Hopefully that fixed the `lint` issue

I've added a test as well

**Comment by benmccann** [comment]
I finally got the tests setup to test both the CJS and ESM versions, but it turns out this wrapper approach doesn't work with Vite

**Comment by benmccann** [comment]
Although that seems to be a Vite bug. It's just ignoring that we're distributing an ESM version and trying to load the CJS version directly, which seems wrong. This PR still seems useful even if Vite is too broken to use it yet

**Pull request closed without merging**
