### PR TITLE
Add cookies from the top websites in the world

### PR DESCRIPTION
**Pull request by jridgewell**
Pulled from Alexa Top 500, visited in an incognito browser.

To progress #77.

### CODE REVIEW

**Comment by ryhinchey** [comment]
this is awesome

**Comment by dougwilson** [comment]
I'm going to see if we can add a script to programmatically update these, or at least document in the code how / where they came from so they can be repliacated or updated by hand later. This is because I believe the point is to benchmark real world cookies, which will change over time by it's nature.

**Comment by ryhinchey** [comment]
> I'm going to see if we can add a script to programmatically update these, or at least document in the code how / where they came from so they can be repliacated or updated by hand later.


I wrote a script tonight to grab the `Set-Cookie` headers from some of the Alexa Top 500.

```js
const fs = require('fs');
const path = require('path');
const got = require('got');

// https://www.alexa.com/topsites
const sites = [
  "https://google.com",
  "https://youtube.com",
  "https://tmall.com",
  "https://facebook.com",
  "https://baidu.com",
  "https://qq.com",
  "https://sohu.com",
  "https://login.tmall.com",
  "https://taobao.com",
  "https://360.cn",
  "https://jd.com",
  "https://yahoo.com",
  "https://wikipedia.org",
  "https://amazon.com",
  "https://sina.com.cn"
]

const userAgent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36";

async function getTopSites() {
  const promises = sites.map(site => got(site, { headers: { 'User-Agent': userAgent } }));

  const responses = await Promise.all(promises);

  return responses;
}

function formatCookies(responses) {
  const cookies = {};

  for (let i = 0; i < responses.length; i++) {
    const response = responses[i];
    const url = sites[i];
    const setCookieHeader = response.headers['set-cookie'];

    if (setCookieHeader) {
      const cookieNameValues = setCookieHeader.map(cookie => cookie.split(';')[0])
      cookies[url] = cookieNameValues.join(';')
    }
  }

  return cookies;
}

function writeData(cookies) {
  const dataDir = path.join(process.cwd(), 'data');
  fs.mkdirSync(dataDir, { recursive: true });

  const dataFile = path.join(process.cwd(), 'data', 'topSites.json');
  fs.writeFileSync(dataFile, JSON.stringify(cookies, null, 2));
}


async function run() {
  const responses = await getTopSites();
  const cookies = formatCookies(responses);
  writeData(cookies);
}

run();
```

the data looks like this
```json
{
  "https://google.com": "1P_JAR=2020-02-21-03;NID=198=yefnUmj6QuKRmy_bOfLbNZzWIJgJm-TRhkvh7skDKA5CcQhy5wsA38FNK3Wu2I4pv2cp4N8wqHDkP75rDOykjniS2Vn5oPd5VO47mmSEyZV784uuQKMUEMFTHluYw5iVsKhSMdSteY_VmSiduZJwlSGOhF8LtBK22PY0R0qG8L4",
  "https://youtube.com": "GPS=1;VISITOR_INFO1_LIVE=RtplrwMaGmI;YSC=lu_rB9eSHX4",
  "https://facebook.com": "fr=1KwjOSMbpo4TxFA2H..BeT01k.tW.AAA.0.0.BeT01k.AWUsyMVW;sb=ZE1PXvb8EsdLuILPp_u_wXtx",
  "https://baidu.com": "BAIDUID=CDABF6C7D9F6004EA9ADC57AB08C7A2A:FG=1;BIDUPSID=CDABF6C7D9F6004EA9ADC57AB08C7A2A;PSTM=1582255461;BAIDUID=CDABF6C7D9F6004EABE8B71FA1CE2AA3:FG=1;delPer=0;BDSVRTM=0;BD_HOME=0;H_PS_PSSID=30747_1448_21102_30824_22160",
  "https://taobao.com": "thw=us",
  "https://yahoo.com": "autorf=deleted;B=4c7t4ntf4ujb4&b=3&s=p2",
  "https://wikipedia.org": "WMF-Last-Access=21-Feb-2020;WMF-Last-Access-Global=21-Feb-2020;GeoIP=US:NJ:Maplewood:40.73:-74.27:v4",
  "https://amazon.com": "skin=noskin;session-id=144-4530930-8024236;session-id-time=2082787201l;i18n-prefs=USD"
}```

Is this along the lines of what you had in mind?  If so, I can clean up the code and make a PR

**Comment by jonchurch** [comment]
@ryhinchey Do you mind opening a PR with this script so we can start getting feedback on it?

**Comment by ryhinchey** [comment]
@jonchurch sorry I haven’t gotten around to doing this yet.  Shooting to raise a pr this week!

**Comment by dougwilson** [comment]
I realize this has sat here forever, but I am working on getting everything merged and released from many of these repos. I took the basics of the script above (thanks! I know there is no PR) and included it to make the benchmark with obfuscated cookie values.

**Pull request closed without merging**
