### PR TITLE
Use correct units for maxAge option

### PR DESCRIPTION
**Pull request by erikmusd**
See @dougwilson comment: https://github.com/jshttp/cookie/issues/65#issuecomment-294358204

### CODE REVIEW

**Comment by blakeembrey** [comment]
No, the package is definitely accepting seconds and not milliseconds. It serializes the integer directly as max age. I believe there was a mistake in that comment and it was corrected later.

**Comment by erikmusd** [comment]
@blakeembrey I'm using `cookie-parser` package and it [delegates the cookie options](https://github.com/expressjs/cookie-parser?tab=readme-ov-file#cookieparsersecret-options) to this package. When I used seconds it doesn't work as intended, I have to use milliseconds. So after seeing some closed issues I thought the problem was here. So maybe cookie-parser is the problem then.

**Comment by blakeembrey** [comment]
There’s nothing I see in cookie parser about writing cookies, it’s probably a different package you’re using?

**Comment by erikmusd** [comment]
@blakeembrey it uses `cookie `as a dependency. And accepts `cookie `options i.e. maxAge, etc.

**Comment by blakeembrey** [comment]
For parsing, but not serializing. I just read over the code. You must be using something else to serialize cookies.

**Comment by blakeembrey** [comment]
Maybe you're using this? https://github.com/expressjs/session?tab=readme-ov-file#cookiemaxage (it mentions using milliseconds, so that package is probably altering the input to seconds before serializing here).

**Comment by erikmusd** [comment]
I'm using:

image

but idk, maybe there is something else modifying it somewhere.

**Comment by blakeembrey** [comment]
That’s correct, req.cookies is the parsed cookies, it’s not for serializing them though. You have no need for maxAge when parsing.

**Comment by erikmusd** [comment]
@blakeembrey my bad, I'm using the` res.cookies` (https://expressjs.com/en/api.html#res.cookie), not` req.cookies`. That's where I'm using milliseconds instead of seconds when creating a cookie. Thanks for helping clarify my misunderstanding. I missed the detail. Thanks for taking your time to check this out! Good day!

**Pull request closed without merging**
